[build]
  base = "sug-dashboard"
  command = "pip install pandas openpyxl google-auth google-api-python-client && python ../process_data.py && npm run build"
  publish = "dist"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
